force-app/main/default/objects/Deployment__c.object
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <displayFormat>D.No.-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deployment_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Deployment Details</relationshipLabel>
        <relationshipName>Deployment_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Detail</label>
    <nameField>
        <label>Deployment Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deployment_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>DataToDel__c</fullName>
        <label>DataToDel</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DataToRollBack__c</fullName>
        <label>DataToRollBack</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DeploymentData__c</fullName>
        <label>DeploymentData</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Deployment Metadatas</relationshipLabel>
        <relationshipName>Deployment_Metadatas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Metadata</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Metadatas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GRM_MetadataRetrieveController.cls
public class GRM_MetadataRetrieveController {    
   
    @AuraEnabled
    public static string RMgetSeletedMetadataMemberMap(string parentId){
        Deployment_Detail__c recordId = [Select Id, Deployment__c from Deployment_Detail__c where Id =: parentId limit 1];
        Deployment_Metadata__c detail=[Select DeploymentData__c from Deployment_Metadata__c where Deployment__c =: recordId.Deployment__c limit 1];
        String obj =detail.DeploymentData__c;
        return obj;
    }
    @AuraEnabled
    public static string RMgetRollbackMetadataMemberMap(string parentId){
        Deployment_Detail__c recordId = [Select Id, Deployment__c from Deployment_Detail__c where Id =: parentId limit 1];
        Deployment_Metadata__c detail=[Select DataToRollBack__c from Deployment_Metadata__c where Deployment__c =: recordId.Deployment__c limit 1];
        String obj =detail.DataToRollBack__c;
        return obj;
    }
    @AuraEnabled
    public static string RMgetDeletedMetadataMemberMap(string parentId){
        Deployment_Detail__c recordId = [Select Id, Deployment__c from Deployment_Detail__c where Id =: parentId limit 1];
        Deployment_Metadata__c detail=[Select DataToDel__c from Deployment_Metadata__c where Deployment__c =: recordId.Deployment__c limit 1];
        String obj =detail.DataToDel__c;
        return obj;
    }
}