force-app/main/default/objects/OrgAuthorizationInfo__c.object
<CustomObject>
    <fields>
        <fullName>AccessToken__c</fullName>
        <label>AccessToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorised__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authorised</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OauthID__c</fullName>
        <description>Org auth id</description>
        <label>OauthID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgType__c</fullName>
        <label>OrgType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RefreshToken__c</fullName>
        <label>RefreshToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>instance_url__c</fullName>
        <label>instance url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>org_name__c</fullName>
        <label>org_name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OrgAuthorizationInfo</label>
    <nameField>
        <label>OrgAuthorizationInfo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgAuthorizationInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgTempData__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to store temporary information for the org</description>
    <fields>
        <fullName>OrgRecordId__c</fullName>
        <label>OrgRecordId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OrgTempData</label>
</CustomObject>

force-app/main/default/objects/SF_Org__c.object
<CustomObject>
    <description>Use to store salesforce org data after authorization.</description>
    <fields>
        <fullName>AccessToken__c</fullName>
        <label>AccessToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorised__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authorized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OauthID__c</fullName>
        <description>Org auth id</description>
        <label>OAuth ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgType__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Production</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RefreshToken__c</fullName>
        <label>RefreshToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>instance_url__c</fullName>
        <label>Instance Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>org_name__c</fullName>
        <label>org_name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SF Org</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SF Orgs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DBUtils.cls
public with sharing class DBUtils {
    public static OrgTempData__c getOrgTemp(){
        return [Select Id, OrgRecordId__c FROM OrgTempData__c WITH SECURITY_ENFORCED LIMIT 1];
    }

    public static List<SF_Org__c> getOrgList(){
        return [SELECT Id, Name, AccessToken__c, Authorised__c, Instance_URL__c, OauthID__c, OrgType__c, Org_Name__c, RefreshToken__c, UserEmail__c FROM SF_Org__c WHERE Name!='' WITH SECURITY_ENFORCED ORDER BY CreatedDate DESC];
    }

    public static SF_Org__c getOrg(String orgId){
        return [SELECT Id, Name, AccessToken__c, Authorised__c, Instance_URL__c, OauthID__c, OrgType__c, Org_Name__c, RefreshToken__c, UserEmail__c  FROM SF_Org__c WHERE Id=:String.escapeSingleQuotes(orgId) WITH SECURITY_ENFORCED LIMIT 1];
    }

    public static List<SF_Org__c> getOrgByName(String name){
        return [SELECT Id FROM SF_Org__c WHERE Name=:String.escapeSingleQuotes(name) WITH SECURITY_ENFORCED LIMIT 1];
    }
    @AuraEnabled
    public static List<SF_Org__c> getAuthorizeOrg(){
        return [SELECT Id, Name, AccessToken__c, Authorised__c, Instance_URL__c, OauthID__c, OrgType__c, Org_Name__c, RefreshToken__c, UserEmail__c FROM SF_Org__c WHERE Authorised__c=true WITH SECURITY_ENFORCED ORDER BY Org_Name__c ASC];
    }

    public static List<Document> getDocs(String fileName){
        return [SELECT Id, Name, FolderId, Body FROM Document WHERE Name = :fileName AND FolderId =:UserInfo.getUserId() WITH SECURITY_ENFORCED LIMIT 1];
    }

    public static String getUrl(String type){
        return type =='Sandbox'?Label.Sandbox_Login_URL:Label.Production_Login_URL;
    }

    public static OrgAuthorizationInfo__c getOrgAuthInfo(String selectedOrg){
        return [SELECT Id, AccessToken__c, OrgType__c, RefreshToken__c, Instance_URL__c FROM OrgAuthorizationInfo__c WHERE Id=:String.escapeSingleQuotes(selectedOrg) WITH SECURITY_ENFORCED LIMIT 1];
    }
}